### ISSUE TITLE
Error should be thrown when attribute does not exist

### ISSUE THREAD

**Issue by tiagofsilva** [guava/matching_exceptions#2]
What we have right now is that #matches ignores non existent field, failing silently. I think this is a real problem as the user could lose some time to find out what is going on, when it's all about a simple typo. It's exemplified in the code below:

```
    begin
      raise CustomError.new("blabla", "custom message")
    rescue ME.matches(/message/, on: :foo)
      rescued = true
```

Maybe just throwing a custom error would be more appropriate in this case?

**Comment by lbrito1** [comment]
I agree. Thoughts @gvc ?

**Comment by gvc** [comment]
I think that failing inside a rescue clause is a bad pattern. One possible workaround for the typo case can be a warning message.
